name: Backend CI/CD

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: localgov-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn -B package

      - name: Run linter (Checkstyle)
        run: mvn checkstyle:check

      - name: Run tests
        run: mvn -B test

      # === CD: Push Docker image to GHCR ===

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build
        run: |
          IMAGE=ghcr.io/${{ github.actor }}/localgov-backend:latest
          IMAGE_LC=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_LC .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker push to GHCR
        run: |
          IMAGE=ghcr.io/${{ github.actor }}/localgov-backend:latest
          IMAGE_LC=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          docker push $IMAGE_LC

      - name: Security scan cu Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/rzvc93/localgov-backend:latest
          format: table
          exit-code: 0
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

